const CONFIG = {
  LIMITS: {
    MAX_SLIDES_FETCH: 50,
    MAX_TOC_SLIDES: 8
  },
  COLORS: {
    PRIMARY: '#1a73e8',
    NAV_BG: '#f1f3f4',
    NAV_TEXT: '#5f6368',
    WHITE: '#ffffff'
  },
  ELEMENTS: {
    NAV_TITLE: 'SMM_NAV_BG',
    NAV_TEXT_TITLE: 'SMM_NAV_TEXT',
    TOC_TITLE: 'SMM_TOC_TITLE'
  }
};

const I18N = {
  en: {
    menu_open_sidebar: "✨ Open Slide Map Maker sidebar",
    menu_quick_create: "🚀 Quick Create",
    menu_add_nav: "🔙 Add Back-Links Only",
    menu_delete_nav: "🗑 Delete Back-Links",
    menu_help: "ⓘ Help / Tutorial",
    
    error_not_enough_slides: "Not enough slides. You need at least 2 slides.",
    error_too_many_slides: "Too many slides. The Table of Contents supports up to 8 slides.",
    error_no_toc_slide: "Table of Contents slide not found. Please create one first.",
    
    quick_create_title: "🚀 Quick Create Contents",
    quick_create_prompt: "A Table of Contents will be created.\nThe title slide will be skipped.",
    quick_create_success_title: "✅ Contents Created!",
    quick_create_success_msg: "Table of Contents slide has been created.\n\nThe slide was automatically moved to the end.",
    
    add_nav_success_title: "✅ Links Added!",
    add_nav_success_msg: "Back-links have been added to %s slides.\n\nClick the slide number in the bottom right corner to return to the contents.",
    
    delete_nav_title: "🗑 Delete Navigation",
    delete_nav_prompt: "Are you sure you want to delete all navigation buttons?\n\n(All elements created by Slide Map Maker in the bottom right corner will be deleted)",
    delete_nav_success_title: "✅ Navigation Deleted",
    delete_nav_success_msg: "Deleted %s navigation elements from %s slides.",
    
    help_html: '<h3>Slide Map Maker Help</h3><p>1. Open sidebar to select slides</p><p>2. Check the slides you want in contents</p><p>3. Click "Create Contents Slide"</p><p>4. Click on thumbnails to navigate</p>',
    
    sidebar_title: "Slide Map Maker",
    sidebar_select_slides: "Select Slides",
    sidebar_selected: "Selected: ",
    sidebar_refresh: "🔄 Refresh Slides",
    sidebar_select_all: "✅ Select All",
    sidebar_deselect_all: "❌ Deselect All",
    sidebar_loading_slides: "Loading slides...",
    sidebar_loading_progress: "Loading slide %s of %s...",
    sidebar_empty_state: "No slides loaded. Click 'Refresh' to load.",
    sidebar_create_toc: "🗂️ Create Contents Slide",
    sidebar_create_nav: "🔙 Create Back-Links",
    sidebar_creating: "Creating...",
    
    toc_title: "Table of Contents",
    notes_hint: "🎯 Clickable presentation contents from %s slides\n💡 Automatically generated by Slide Map Maker 🕐 %s"
  },
  ru: {
    menu_open_sidebar: "✨ Открыть панель Slide Map Maker",
    menu_quick_create: "🚀 Быстрое создание",
    menu_add_nav: "🔙 Добавить только обратные ссылки",
    menu_delete_nav: "🗑 Удалить обратные ссылки",
    menu_help: "ⓘ Справка / Инструкция",
    
    error_not_enough_slides: "Недостаточно слайдов. Для создания содержания нужно хотя бы 2 слайда.",
    error_too_many_slides: "Слишком много слайдов. Создание содержания поддерживается для максимум 8 слайдов.",
    error_no_toc_slide: "Слайд содержания не найден. Пожалуйста, сначала создайте его.",
    
    quick_create_title: "🚀 Быстрое создание содержания",
    quick_create_prompt: "Будет создано содержание.\n\nТитульный слайд будет пропущен.",
    quick_create_success_title: "✅ Содержание создано!",
    quick_create_success_msg: "Создан слайд содержания.\n\nСлайд автоматически перемещен в конец презентации.",
    
    add_nav_success_title: "✅ Ссылки добавлены!",
    add_nav_success_msg: "Обратные ссылки добавлены на %s слайдов.\n\nНажмите на номер слайда в правом нижнем углу, чтобы вернуться к содержанию.",
    
    delete_nav_title: "🗑 Удаление навигации",
    delete_nav_prompt: "Вы уверены, что хотите удалить все кнопки навигации?\n\n(Будут удалены все элементы в правом нижнем углу слайдов, созданные Slide Map Maker)",
    delete_nav_success_title: "✅ Навигация удалена",
    delete_nav_success_msg: "Удалено %s элементов навигации с %s слайдов.",
    
    help_html: '<h3>Справка Slide Map Maker</h3><p>1. Откройте панель для выбора слайдов</p><p>2. Отметьте нужные слайды</p><p>3. Нажмите "Создать слайд содержания"</p><p>4. Кликайте по миниатюрам для навигации</p>',
    
    sidebar_title: "Slide Map Maker",
    sidebar_select_slides: "Выберите слайды",
    sidebar_selected: "Выбрано: ",
    sidebar_refresh: "🔄 Обновить слайды",
    sidebar_select_all: "✅ Выбрать всё",
    sidebar_deselect_all: "❌ Сбросить выбор",
    sidebar_loading_slides: "Загрузка слайдов...",
    sidebar_loading_progress: "Загрузка слайда %s из %s...",
    sidebar_empty_state: "Слайды не загружены. Нажмите 'Обновить' чтобы загрузить список.",
    sidebar_create_toc: "🗂️ Создать слайд содержания",
    sidebar_create_nav: "🔙 Создать обратные ссылки на содержание",
    sidebar_creating: "Создание...",
    
    toc_title: "Содержание",
    notes_hint: "🎯 Кликабельное содержание презентации из %s слайдов\n💡 Автоматически создано с помощью Slide Map Maker 🕐 %s"
  }
};

function getText(key) {
  try {
    const locale = Session.getActiveUserLocale();
    const lang = (locale && locale.toLowerCase().indexOf('ru') !== -1) ? 'ru' : 'en';
    return I18N[lang][key] || I18N['en'][key] || key;
  } catch (e) {
    return I18N['en'][key] || key; // Default to English if context is missing
  }
}
